# Generated by Django 6.0 on 2025-12-25 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_email_otp_user_is_email_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_otp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_email_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_created_at',
        ),
    ]
