# Generated by Django 6.0 on 2026-03-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_message_deleted_by_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.URLField(blank=True, null=True),
        ),
    ]
